---

- name: Create dataset config
  template:
    src: put_items.json.j2
    dest: "{{ io_runner_dir }}/put_items.json"

- set_fact:
    io_blaster_config: put_items.json

- name: Put items
  shell: "{{ io_runner_dir }}/io_blaster -c {{ io_runner_dir }}/{{ io_blaster_config }} -o {{ io_runner_results_dir }}/put_items.log -s {{ io_runner_results_dir }}/put_items_stats"

