---

- name: Create config for reading
  template:
    src: get_items.json.j2
    dest: "{{ io_runner_dir }}/get_items.json"

- set_fact:
    io_blaster_config: get_items.json

- name: Read items
  shell: "{{ io_runner_dir }}/io_blaster -c {{ io_runner_dir }}/{{ io_blaster_config }} -o {{ io_runner_results_dir }}/get_items.log -s {{ io_runner_results_dir }}/get_items_stats"
