---

- name: Create config for reading
  template:
    src: warm_1200_items.json.j2
    dest: "{{ io_runner_dir }}/warm_1200_items.json"

- set_fact:
    io_blaster_config: warm_1200_items.json

- name: Warm items
  shell: "{{ io_runner_dir }}/io_blaster -c {{ io_runner_dir }}/{{ io_blaster_config }} -o {{ io_runner_results_dir }}/get_items"
