---

- name: Create dataset config
  template:
    src: put_obj.json.j2
    dest: "{{ io_runner_dir }}/put_obj.json"

- set_fact:
    io_blaster_config: put_obj.json

- name: Put items
  shell: "{{ io_runner_dir }}/io_blaster -c {{ io_runner_dir }}/{{ io_blaster_config }} -o {{ io_runner_results_dir }}/put_obj.log -s {{ io_runner_results_dir }}/put_obj_stats"

