---

- name: Create config for reading
  template:
    src: get_items_with_attr_1m.json.j2
    dest: "{{ io_runner_dir }}/get_items_with_attr_1m.json"

- set_fact:
    io_blaster_config: get_items_with_attr_1m.json

- name: Get 1M items
  shell: "{{ io_runner_dir }}/io_blaster -c {{ io_runner_dir }}/{{ io_blaster_config }} -o {{ io_runner_results_dir }}/get_items"
