---

- set_fact:
    stage: before_start

- include_tasks: get_stats.yml
  when: inventory_hostname in groups['data_nodes']

- include_tasks: create_dataset.yml
  when: inventory_hostname in groups['app_nodes']

- include_tasks: warm_items.yml
  when: inventory_hostname in groups['app_nodes']

- set_fact:
    stage: after_warming

- include_tasks: get_stats.yml
  when: inventory_hostname in groups['data_nodes']

- include_tasks: scan_container.yml
  when: inventory_hostname in groups['app_nodes']

- set_fact:
    stage: after_scan

- include_tasks: get_stats.yml
  when: inventory_hostname in groups['data_nodes']

- include_tasks: warm_items.yml
  when: inventory_hostname in groups['app_nodes']

- set_fact:
    stage: final

- include_tasks: get_stats.yml
  when: inventory_hostname in groups['data_nodes']

- name: Collect results
  shell: "stats_reader.py -f {{ item }}.json >> combined_results.txt"
  args:
    chdir: /home/iguazio/io_runner
    executable: /bin/bash

- name: Cat results file
  command: cat /home/iguazio/io_runner/combined_results.txt
  register: results

- name: Print results
  debug:
    msg: "{{ results.stdout_lines }}"

